# Buildkite pipeline for Orchestrate (Rust)

steps:
  - group: ":microscope: Test"
    key: "lint-and-test"
    steps:
      - id: "cargo-fmt"
        label: ":rust: Cargo Fmt"
        commands:
          - eval "$(./bin/hermit env --activate)"
          - cargo fmt --all -- --check

      - id: "cargo-clippy"
        label: ":rust: Cargo Clippy"
        commands:
          - eval "$(./bin/hermit env --activate)"
          - cargo clippy --all-targets --all-features -- -D warnings

      - id: "cargo-build"
        label: ":rust: Cargo Build"
        commands:
          - eval "$(./bin/hermit env --activate)"
          - cargo build --release

      - id: "cargo-test"
        label: ":rust: Cargo Test"
        commands:
          - eval "$(./bin/hermit env --activate)"
          - cargo test --all-features
